#!/usr/bin/env bash
#
# yafs
# Yet Another Fetch Script
#

# Distro
distro=$(source /etc/os-release; echo $NAME)

# Get Desktop Enviroment
wm=$(xprop -root _NET_SUPPORTING_WM_CHECK)
wm=${wm##* }
wm=$(xprop -id "$wm" _NET_WM_NAME)
wm="$(echo $wm | cut -d'"' -f 2)"

# Shell
shell=$SHELL

# Uptime
uptime=$(uptime -p | cut -c 4-)

# Colors
blue="$(tput setaf 4)"
green="$(tput setaf 2)"
re="$(tput sgr0)"

# Show info
cat <<EOF

${re}$(tput bold)${blue}OS - ${re}${green}$distro
${re}$(tput bold)${blue}WM - ${re}${green}$wm
${re}$(tput bold)${blue}SH - ${re}${green}$shell
${re}$(tput bold)${blue}UP - ${re}${green}$uptime

EOF
